version: '3.8'

services:
  mysql:
    image: juricastellani/mypublicrepo-db:1.0.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - myNetwork

  backend:
    image: juricastellani/mypublicrepo:1.0.0
    container_name: spring-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - myNetwork

  frontend:
    image: juricastellani/mypublicrepo-frontend:1.0.0
    container_name: angular-app
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4300:4300"
    networks:
      - myNetwork

networks:
  myNetwork:

volumes:
  mysql-data:
