FROM node:alpine
RUN mkdir angular
COPY . /angular
WORKDIR /angular
RUN rm -rf /.angular
RUN rm -rf /node_modules
RUN rm package-lock.json
RUN npm install -g @angular/cli
RUN npm install --verbose
EXPOSE 4300
CMD ["npm", "run", "serve:prod"]
