FROM node:18-alpine3.20 as angular
RUN apk add --no-cache curl

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build:prod

FROM httpd:alpine3.15
RUN apk add --no-cache curl
WORKDIR /usr/local/apache2/htdocs
COPY --from=angular /app/dist/my-first-project .
