FROM eclipse-temurin:21-jre
ENV DB_SCHEMA: mysqlappdb \
    DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect \
    DB_URL: jdbc:mysql://mysql-db:3306/mysqlappdb?allowPublicKeyRetrieval=true&useSSL=false \
    DB_USR: mysqluser \
    DB_PWD: mysqlpassword \
    DB_DRIVER: com.mysql.cj.jdbc.Driver

WORKDIR /app
COPY backend/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
