version: '3.8'

services:
  mysql:
    image: juricastellani/mypublicrepo-db:1.0.0
    container_name: mysql-db
    networks:
      - myNetwork

  backend:
    image: juricastellani/mypublicrepo:1.0.0
    container_name: spring-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SCHEMA: mysqlappdb
      DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      DB_URL: jdbc:mysql://mysql-db:3306/mysqlappdb?allowPublicKeyRetrieval=true&useSSL=false
      DB_USR: mysqluser
      DB_PWD: mysqlpassword
      DB_DRIVER: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    networks:
      - myNetwork

  frontend:
    image: juricastellani/mypublicrepo-frontend:1.0.0
    container_name: angular-app
    depends_on:
      - backend

networks:
  myNetwork:

volumes:
  mysql-data:
