name: Integration Test
run-name: "🚀 ${{  github.actor  }} - integration-test"
on:
  workflow_run:
    workflows: ["Publish Frontend Image"]
    types:
      - completed
jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker/docker-compose.yaml"

      - name: Execute tests in the running services
        run: |
          cd docker
          docker compose up -d

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app..."
          sleep 20 # or implement a better healthcheck with curl retries

      - name: Run API tests
        run: |
          curl --fail http://localhost:8080/api/companies || exit 1
