name: Integration Test
run-name: "🚀 ${{  github.actor  }} - integration-test"
on:
  workflow_run:
    workflows: ["Publish Frontend Image", "Publish Backend Image"]
    types:
      - completed
jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker/docker-compose.yaml"

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app..."
          sleep 10

      - name: Run API tests
        run: |
          curl --fail http://localhost:8080/api/companies || exit 1

      - name: Check Frontend Availability
        run: |
          curl --fail -s http://localhost:4300 > /dev/null
          echo "Frontend is available"

      # Frontend content check
      - name: Check Frontend Content
        run: |
          curl --fail -s http://localhost:4300/browser | grep -q "<title>" || exit 1
          echo "Frontend contains expected elements"

      # Optional: Setup for more advanced frontend testing
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
