name: Integration Test
run-name: "🚀 ${{  github.actor  }} - integration-test"
on:
  workflow_run:
    workflows: ["Publish Image"]
    types:
      - completed
jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: latest

      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app..."
          sleep 20 # or implement a better healthcheck with curl retries

      - name: Run API tests
        run: |
          curl --fail http://localhost:8080/health || exit 1
          curl --fail http://localhost:8080/api/your-endpoint || exit 1
