name: Publish Frontend Image
run-name: "🚀 ${{  github.actor  }} - publish frontend image - last commit: \"${{  github.event.head_commit.message  }}\""

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.*'
      - 'backend/**'
      - 'LICENSE'
      - 'images/**'
      - 'examples/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure npm registry
        working-directory: ./frontend
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Angular app
        working-directory: ./frontend
        run: npm run build --configuration production

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mypublicrepo-frontend:1.0.0
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mypublicrepo-frontend:1.0.0
          cache-to: type=inline